language: r
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

env:
   global:
     - R_BUILD_ARGS="--no-manual"
     - R_CHECK_ARGS="--as-cran --no-manual"

notifications:
 email:
   on_success: never
   on_failure: never
