language: r
sudo: false
cache: packages
dist: trusty

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_BUILD_ARGS="--no-manual --no-build-vignettes"
     - R_CHECK_ARGS="--as-cran --no-manual --no-build-vignettes"

notifications:
 email:
   on_success: change
   on_failure: change
